Clean up, prep for version update

diff --git a/OpenRA-OW2023-02-25/Makefile b/OpenRA-OW2023-02-25/Makefile
--- a/OpenRA-OW2023-02-25/Makefile
+++ b/OpenRA-OW2023-02-25/Makefile
@@ -9,55 +9,62 @@
 # to compile using system libraries for native dependencies, run:
 #   make [RUNTIME=net6] TARGETPLATFORM=unix-generic
 #
-# to remove the files created by compiling, run:
-#   make clean
-#
-# to set the mods version, run:
-#   make version [VERSION="custom-version"]
-#
-# to check lua scripts for syntax errors, run:
-#   make check-scripts
-#
-# to check the engine and your mod dlls for StyleCop violations, run:
-#   make [RUNTIME=net6] check
-#
-# to check your mod yaml for errors, run:
+# to check the official mods for erroneous yaml files, run:
 #   make [RUNTIME=net6] test
 #
-# the following are internal sdk helpers that are not intended to be run directly:
-#   make check-variables
-#   make check-sdk-scripts
-#   make check-packaging-scripts
+# to check the engine and official mod dlls for code style violations, run:
+#   make [RUNTIME=net6] check
+#
+# to compile and install Red Alert, Tiberian Dawn, and Dune 2000, run:
+#   make [RUNTIME=net6] [prefix=/foo] [bindir=/bar/bin] install
+#
+# to compile and install Red Alert, Tiberian Dawn, and Dune 2000
+# using system libraries for native dependencies, run:
+#   make [prefix=/foo] [bindir=/bar/bin] TARGETPLATFORM=unix-generic install
+#
+# to install FreeDesktop startup scripts, desktop files, icons, and MIME metadata
+#   make install-linux-shortcuts
+#
+# to install FreeDesktop AppStream metadata
+#   make install-linux-appdata
+#
+# to install the Unix man page
+#   make install-man
+#
+# for help, run:
+#   make help
+#
 
-.PHONY: check-sdk-scripts check-packaging-scripts check-variables engine all clean version check-scripts check test
-.DEFAULT_GOAL := all
+######################### UTILITIES/SETTINGS ###########################
+#
+# Install locations for local installs and downstream packaging
+prefix ?= /usr/local
+datarootdir ?= $(prefix)/share
+datadir ?= $(datarootdir)
+mandir ?= $(datarootdir)/man/
+bindir ?= $(prefix)/bin
+libdir ?= $(prefix)/lib
+gameinstalldir ?= $(libdir)/openra
 
-PYTHON = $(shell command -v python3 2> /dev/null)
-ifeq ($(PYTHON),)
-PYTHON = $(shell command -v python 2> /dev/null)
-endif
-ifeq ($(PYTHON),)
-$(error "The OpenRA mod SDK requires python.")
-endif
-
-VERSION = $(shell git name-rev --name-only --tags --no-undefined HEAD 2>/dev/null || echo git-`git rev-parse --short HEAD`)
-MOD_ID = $(shell cat user.config mod.config 2> /dev/null | awk -F= '/MOD_ID/ { print $$2; exit }')
-ENGINE_DIRECTORY = $(shell cat user.config mod.config 2> /dev/null | awk -F= '/ENGINE_DIRECTORY/ { print $$2; exit }')
-MOD_SEARCH_PATHS = "$(shell $(PYTHON) -c "import os; print(os.path.realpath('.'))")/mods,./mods"
-
-MANIFEST_PATH = "mods/$(MOD_ID)/mod.yaml"
-HAS_LUAC = $(shell command -v luac 2> /dev/null)
-LUA_FILES = $(shell find mods/*/maps/* -iname '*.lua' 2> /dev/null)
-MOD_SOLUTION_FILES = $(shell find . -maxdepth 1 -iname '*.sln' 2> /dev/null)
-
+# Toolchain
+CWD = $(shell pwd)
 MSBUILD = msbuild -verbosity:m -nologo
 DOTNET = dotnet
+MONO = mono
+RM = rm
+RM_R = $(RM) -r
+RM_F = $(RM) -f
+RM_RF = $(RM) -rf
 
 RUNTIME ?= net6
 CONFIGURATION ?= Release
 DOTNET_RID = $(shell ${DOTNET} --info | grep RID: | cut -w -f3)
 ARCH_X64 = $(shell echo ${DOTNET_RID} | grep x64)
 
+# Only for use in target version:
+VERSION := $(shell git name-rev --name-only --tags --no-undefined HEAD 2>/dev/null || (c=$$(git rev-parse --short HEAD 2>/dev/null) && echo git-$$c))
+
+# Detect target platform for dependencies if not given by the user
 ifndef TARGETPLATFORM
 UNAME_S := $(shell uname -s)
 UNAME_M := $(shell uname -m)
@@ -80,119 +87,125 @@ endif
 endif
 endif
 
-check-sdk-scripts:
-	@awk '/\r$$/ { exit(1); }' mod.config || (printf "Invalid mod.config format: file must be saved using unix-style (CR, not CRLF) line endings.\n"; exit 1)
-	@if [ ! -x "fetch-engine.sh" ] || [ ! -x "launch-dedicated.sh" ] || [ ! -x "launch-game.sh" ] || [ ! -x "utility.sh" ]; then \
-		echo "Required SDK scripts are not executable:"; \
-		if [ ! -x "fetch-engine.sh" ]; then \
-			echo "   fetch-engine.sh"; \
-		fi; \
-		if [ ! -x "launch-dedicated.sh" ]; then \
-			echo "   launch-dedicated.sh"; \
-		fi; \
-		if [ ! -x "launch-game.sh" ]; then \
-			echo "   launch-game.sh"; \
-		fi; \
-		if [ ! -x "utility.sh" ]; then \
-			echo "   utility.sh"; \
-		fi; \
-		echo "Repair their permissions and try again."; \
-		echo "If you are using git you can repair these permissions by running"; \
-		echo "   git update-index --chmod=+x *.sh"; \
-		echo "and commiting the changed files to your repository."; \
-		exit 1; \
-	fi
-
-check-packaging-scripts:
-	@if [ ! -x "packaging/package-all.sh" ] || [ ! -x "packaging/linux/buildpackage.sh" ] || [ ! -x "packaging/macos/buildpackage.sh" ] || [ ! -x "packaging/windows/buildpackage.sh" ]; then \
-		echo "Required SDK scripts are not executable:"; \
-		if [ ! -x "packaging/package-all.sh" ]; then \
-			echo "   packaging/package-all.sh"; \
-		fi; \
-		if [ ! -x "packaging/linux/buildpackage.sh" ]; then \
-			echo "   packaging/linux/buildpackage.sh"; \
-		fi; \
-		if [ ! -x "packaging/macos/buildpackage.sh" ]; then \
-			echo "   packaging/macos/buildpackage.sh"; \
-		fi; \
-		if [ ! -x "packaging/windows/buildpackage.sh" ]; then \
-			echo "   packaging/windows/buildpackage.sh"; \
-		fi; \
-		echo "Repair their permissions and try again."; \
-		echo "If you are using git you can repair these permissions by running"; \
-		echo "   git update-index --chmod=+x *.sh"; \
-		echo "in the directories containing the affected files"; \
-		echo "and commiting the changed files to your repository."; \
-		exit 1; \
-	fi
-
-check-variables:
-	@if [ -z "$(MOD_ID)" ] || [ -z "$(ENGINE_DIRECTORY)" ]; then \
-		echo "Required mod.config variables are missing:"; \
-		if [ -z "$(MOD_ID)" ]; then \
-			echo "   MOD_ID"; \
-		fi; \
-		if [ -z "$(ENGINE_DIRECTORY)" ]; then \
-			echo "   ENGINE_DIRECTORY"; \
-		fi; \
-		echo "Repair your mod.config (or user.config) and try again."; \
-		exit 1; \
-	fi
-
-engine: check-variables check-sdk-scripts
-	@./fetch-engine.sh || (printf "Unable to continue without engine files\n"; exit 1)
-	@cd $(ENGINE_DIRECTORY) && make RUNTIME=$(RUNTIME) TARGETPLATFORM=$(TARGETPLATFORM) all
-
-all: engine
+##################### DEVELOPMENT BUILDS AND TESTS #####################
+#
+all:
+	@echo "Compiling in ${CONFIGURATION} mode..."
 ifeq ($(RUNTIME), mono)
-	@command -v $(MSBUILD) >/dev/null || (echo "OpenRA requires the '$(MSBUILD)' tool provided by Mono >= 6.4."; exit 1)
-ifneq ("$(MOD_SOLUTION_FILES)","")
-	@find . -maxdepth 1 -name '*.sln' -exec $(MSBUILD) -t:Build -restore -p:Configuration=${CONFIGURATION} -p:TargetPlatform=$(TARGETPLATFORM) -p:Mono=true \;
-endif
+	@command -v $(firstword $(MSBUILD)) >/dev/null || (echo "OpenRA requires the '$(MSBUILD)' tool provided by Mono >= 6.4."; exit 1)
+	@$(MSBUILD) -t:Build -restore -p:Configuration=${CONFIGURATION} -p:TargetPlatform=$(TARGETPLATFORM)
 else
-	@find . -maxdepth 1 -name '*.sln' -exec $(DOTNET) build -c ${CONFIGURATION} -p:TargetPlatform=$(TARGETPLATFORM) \;
+	@$(DOTNET) build -c ${CONFIGURATION} -nologo -p:TargetPlatform=$(TARGETPLATFORM)
 endif
+ifeq ($(TARGETPLATFORM), unix-generic)
+	@./configure-system-libraries.sh
+endif
+	@./fetch-geoip.sh
 
-clean: engine
-ifneq ("$(MOD_SOLUTION_FILES)","")
-ifeq ($(RUNTIME), mono)
-	@find . -maxdepth 1 -name '*.sln' -exec $(MSBUILD) -t:clean \;
-else
-	@find . -maxdepth 1 -name '*.sln' -exec $(DOTNET) clean \;
-endif
-endif
-	@cd $(ENGINE_DIRECTORY) && make clean
+# dotnet clean and msbuild -t:Clean leave files that cause problems when switching between mono/dotnet
+# Deleting the intermediate / output directories ensures the build directory is actually clean
+clean:
+	@-$(RM_RF) ./bin ./*/obj
+	@-$(RM_F) IP2LOCATION-LITE-DB1.IPV6.BIN.ZIP
 
-version: check-variables
-	@sh -c '. $(ENGINE_DIRECTORY)/packaging/functions.sh; set_mod_version $(VERSION) $(MANIFEST_PATH)'
-	@printf "Version changed to $(VERSION).\n"
-
-check-scripts: check-variables
-ifeq ("$(HAS_LUAC)","")
-	@printf "'luac' not found.\n" && exit 1
-endif
+check:
 	@echo
-	@echo "Checking for Lua syntax errors..."
-ifneq ("$(LUA_FILES)","")
-	@luac -p $(LUA_FILES)
-endif
-
-check: engine
-ifneq ("$(MOD_SOLUTION_FILES)","")
 	@echo "Compiling in Debug mode..."
 ifeq ($(RUNTIME), mono)
 # Enabling EnforceCodeStyleInBuild and GenerateDocumentationFile as a workaround for some code style rules (in particular IDE0005) being bugged and not reporting warnings/errors otherwise.
-	@$(MSBUILD) -t:build -restore -p:Configuration=Debug -warnaserror -p:TargetPlatform=$(TARGETPLATFORM) -p:Mono=true -p:EnforceCodeStyleInBuild=true -p:GenerateDocumentationFile=true
+	@$(MSBUILD) -t:build -restore -p:Configuration=Debug -warnaserror -p:TargetPlatform=$(TARGETPLATFORM) -p:EnforceCodeStyleInBuild=true -p:GenerateDocumentationFile=true
 else
 # Enabling EnforceCodeStyleInBuild and GenerateDocumentationFile as a workaround for some code style rules (in particular IDE0005) being bugged and not reporting warnings/errors otherwise.
 	@$(DOTNET) build -c Debug -nologo -warnaserror -p:TargetPlatform=$(TARGETPLATFORM) -p:EnforceCodeStyleInBuild=true -p:GenerateDocumentationFile=true
 endif
+ifeq ($(TARGETPLATFORM), unix-generic)
+	@./configure-system-libraries.sh
 endif
+	@echo
 	@echo "Checking for explicit interface violations..."
-	@./utility.sh --check-explicit-interfaces
+	@./utility.sh all --check-explicit-interfaces
+	@echo
 	@echo "Checking for incorrect conditional trait interface overrides..."
-	@./utility.sh --check-conditional-trait-interface-overrides
+	@./utility.sh all --check-conditional-trait-interface-overrides
+
+check-scripts:
+	@echo
+	@echo "Checking for Lua syntax errors..."
+	@find lua/ mods/*/{maps,scripts}/ -iname "*.lua" -print0 | xargs -0n1 luac -p
 
 test: all
-	@echo "Testing $(MOD_ID) mod MiniYAML..."
-	@./utility.sh --check-yaml
+	@echo
+	@echo "Testing Tiberian Sun mod MiniYAML..."
+	@./utility.sh ts --check-yaml
+	@echo
+	@echo "Testing Dune 2000 mod MiniYAML..."
+	@./utility.sh d2k --check-yaml
+	@echo
+	@echo "Testing Tiberian Dawn mod MiniYAML..."
+	@./utility.sh cnc --check-yaml
+	@echo
+	@echo "Testing Red Alert mod MiniYAML..."
+	@./utility.sh ra --check-yaml
+
+############# LOCAL INSTALLATION AND DOWNSTREAM PACKAGING ##############
+#
+version: VERSION mods/ra/mod.yaml mods/cnc/mod.yaml mods/d2k/mod.yaml mods/ts/mod.yaml mods/modcontent/mod.yaml mods/all/mod.yaml
+ifeq ($(VERSION),)
+	$(error Unable to determine new version (requires git or override of variable VERSION))
+endif
+	@sh -c '. ./packaging/functions.sh; set_engine_version "$(VERSION)" .'
+	@sh -c '. ./packaging/functions.sh; set_mod_version "$(VERSION)" mods/ra/mod.yaml mods/cnc/mod.yaml mods/d2k/mod.yaml mods/ts/mod.yaml mods/modcontent/mod.yaml mods/all/mod.yaml'
+
+install:
+	@sh -c '. ./packaging/functions.sh; install_assemblies $(CWD) $(DESTDIR)$(gameinstalldir) $(TARGETPLATFORM) $(RUNTIME) True True True'
+	@sh -c '. ./packaging/functions.sh; install_data $(CWD) $(DESTDIR)$(gameinstalldir) cnc d2k ra'
+
+install-linux-shortcuts:
+	@sh -c '. ./packaging/functions.sh; install_linux_shortcuts $(CWD) "$(DESTDIR)" "$(gameinstalldir)" "$(bindir)" "$(datadir)" "$(shell head -n1 VERSION)" cnc d2k ra'
+
+install-linux-appdata:
+	@sh -c '. ./packaging/functions.sh; install_linux_appdata $(CWD) "$(DESTDIR)" "$(datadir)" cnc d2k ra'
+
+install-man: all
+	@mkdir -p $(DESTDIR)$(mandir)/man6/
+	@./utility.sh all --man-page > $(DESTDIR)$(mandir)/man6/openra.6
+
+help:
+	@echo 'to compile, run:'
+	@echo '  make'
+	@echo
+	@echo 'to compile using Mono (version 6.4 or greater) instead of .NET 6, run:'
+	@echo '  make RUNTIME=mono'
+	@echo
+	@echo 'to compile using system libraries for native dependencies, run:'
+	@echo '  make [RUNTIME=net6] TARGETPLATFORM=unix-generic'
+	@echo
+	@echo 'to check the official mods for erroneous yaml files, run:'
+	@echo '  make [RUNTIME=net6] test'
+	@echo
+	@echo 'to check the engine and official mod dlls for code style violations, run:'
+	@echo '  make [RUNTIME=net6] check'
+	@echo
+	@echo 'to compile and install Red Alert, Tiberian Dawn, and Dune 2000 run:'
+	@echo '  make [RUNTIME=net6] [prefix=/foo] [TARGETPLATFORM=unix-generic] install'
+	@echo
+	@echo 'to compile and install Red Alert, Tiberian Dawn, and Dune 2000'
+	@echo 'using system libraries for native dependencies, run:'
+	@echo '   make [RUNTIME=net6] [prefix=/foo] [bindir=/bar/bin] TARGETPLATFORM=unix-generic install'
+	@echo
+	@echo 'to install FreeDesktop startup scripts, desktop files, icons, and MIME metadata'
+	@echo '  make install-linux-shortcuts'
+	@echo
+	@echo 'to install FreeDesktop AppStream metadata'
+	@echo '  make install-linux-appdata'
+	@echo
+	@echo 'to install a Unix man page'
+	@echo '  make install-man'
+
+########################### MAKEFILE SETTINGS ##########################
+#
+.DEFAULT_GOAL := all
+
+.SUFFIXES:
+
+.PHONY: all clean check check-scripts test version install install-linux-shortcuts install-linux-appdata install-man help
